### ISSUE TITLE
error: `block in materia lize': Could not find ffi-1.9.10 in any of the sources (Bundler::GemNotFound)`

### ISSUE THREAD

**Issue by sindhus** [aigarsdz/brume#11]
From a fresh clone, when I run `jekyll serve` I get this:

```
➜  brume git:(master) jekyll serve
/Users/sindhus/.rvm/gems/ruby-2.2.1/gems/bundler-1.12.5/lib/bundler/spec_set.rb:95:in `block in materia
lize': Could not find ffi-1.9.10 in any of the sources (Bundler::GemNotFound)
        from /Users/sindhus/.rvm/gems/ruby-2.2.1/gems/bundler-1.12.5/lib/bundler/spec_set.rb:88:in `map
!'
        from /Users/sindhus/.rvm/gems/ruby-2.2.1/gems/bundler-1.12.5/lib/bundler/spec_set.rb:88:in `mat
erialize'
        from /Users/sindhus/.rvm/gems/ruby-2.2.1/gems/bundler-1.12.5/lib/bundler/definition.rb:140:in `
specs'
        from /Users/sindhus/.rvm/gems/ruby-2.2.1/gems/bundler-1.12.5/lib/bundler/definition.rb:185:in `
specs_for'

        from /Users/sindhus/.rvm/gems/ruby-2.2.1/gems/bundler-1.12.5/lib/bundler/definition.rb:174:in `
requested_specs'
        from /Users/sindhus/.rvm/gems/ruby-2.2.1/gems/bundler-1.12.5/lib/bundler/environment.rb:19:in `
requested_specs'
        from /Users/sindhus/.rvm/gems/ruby-2.2.1/gems/bundler-1.12.5/lib/bundler/runtime.rb:14:in `setu
p'
        from /Users/sindhus/.rvm/gems/ruby-2.2.1/gems/bundler-1.12.5/lib/bundler.rb:95:in `setup'
        from /Users/sindhus/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:38:in `
require_from_bundler'
        from /Users/sindhus/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.1/bin/jekyll:13:in `<top (required)>'
        from /Users/sindhus/.rvm/gems/ruby-2.2.1/bin/jekyll:23:in `load'
        from /Users/sindhus/.rvm/gems/ruby-2.2.1/bin/jekyll:23:in `<main>'
        from /Users/sindhus/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
        from /Users/sindhus/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

How do I fix this?

Thanks!

**Comment by aigarsdz** [comment]
Sorry for the late response. This error was caused by Gemfile.lock file which I forgot to add to .gitignore and it had outdated gem dependencies. It should be fixed in cbe91e8da2e8674f2f2a8f44921594101ffcdc12.

**Comment by sindhus** [comment]
Thanks! am no longer using jekyll (switched to nikola), do you have the same theme for nikola?

**Comment by aigarsdz** [comment]
I haven't used nikola, but it should be easy to port this theme to any other static site generator.
